---
- name: Set up Apache Web Server
  hosts: "{{ hosts_filter_linux | default('all') }}"
  become: true
  
  tasks:

    - include_role:
        name: "linux_apache"



    - name: Show webserver details
      debug: 
        msg: "The Server is available at http://{{ ansible_host }}"